query retrievePosts($title: String, $content: String, $period: periodInput) {
  retrievePosts: retrievePosts(
    title: $title
    content: $content
    period: $period
  ) {
    _id
    title
    content
    author {
      email
    }
    like
    updated
    created
  }
}
