query retrievePosts($keywords: keywordsInput, $period: periodInput, $range: rangeInput) {
  retrievePosts: retrievePosts(
    keywords: $keywords
    period: $period
    range: $range
  ) {
    _id
    title
    content
    author {
      email
    }
    like
    updated
    created
  }
}
