mutation updatePost(
  $_id: String!
  $title: String!
  $content: String!
  $slug: String
) {
  updatePost: updatePost(
    _id: $_id
    title: $title
    content: $content
    slug: $slug
  ) {
    _id
    title
    content
    author {
      email
    }
  }
}
