query posts($title: String) {
  postsByTitle: postsByTitle(title: $title) {
    posts {
      post {
        title
        content
      }
    }
  }
  postsByAuthor: postsByAuthor(title: $title) {
    posts {
      post {
        title
        content
      }
    }
  }
}
